compute_environment: LOCAL_MACHINE
debug: false
distributed_type: DEEPSPEED
deepspeed_config:
  deepspeed_config_file: "/home/fs71550/simeon/LLMs-on-supercomputers/tooling/config/ds_config.json"
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
downcast_bf16: 'yes'
machine_rank: 0
main_training_function: main
num_machines: 2
num_processes: 4
rdzv_backend: static
same_network: true
use_cpu: false
