compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: bf16
num_machines: 2
num_processes: 4
machine_rank: 0
rdzv_backend: static
dynamo_backend: 'inductor'
same_network: true
